# Generated by Django 4.2 on 2023-07-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_genre"),
        ("common", "0003_alter_follow_follower_alter_follow_following_votes_and_more"),
    ]

    operations = []
