# Generated by Django 4.2 on 2023-07-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_user_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                default="/static/abc.jpg", null=True, upload_to="profiles/"
            ),
        ),
    ]
