# Generated by Django 4.2 on 2023-07-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_alter_user_profile_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mylist",
            old_name="movie_id",
            new_name="movie_title",
        ),
        migrations.RenameField(
            model_name="votes",
            old_name="movie_id",
            new_name="movie_title",
        ),
        migrations.RemoveField(
            model_name="review",
            name="movie_id",
        ),
        migrations.AddField(
            model_name="review",
            name="movie_title",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
