# Generated by Django 4.2 on 2023-07-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_rename_movie_id_mylist_movie_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestnote",
            name="main",
        ),
        migrations.RemoveField(
            model_name="guestnote",
            name="writer",
        ),
        migrations.RemoveField(
            model_name="mylist",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="votes",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_img",
            field=models.ImageField(
                default="profiles/cbuchu.png", upload_to="profiles/"
            ),
        ),
        migrations.DeleteModel(
            name="follow",
        ),
        migrations.DeleteModel(
            name="GuestNote",
        ),
        migrations.DeleteModel(
            name="mylist",
        ),
        migrations.DeleteModel(
            name="review",
        ),
        migrations.DeleteModel(
            name="votes",
        ),
    ]
