# Generated by Django 4.1.10 on 2023-07-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('origin_country', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('iso_3166_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('iso_639_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('adult', models.BooleanField(default=False)),
                ('backdrop_path', models.CharField(max_length=100)),
                ('belongs_to_collection', models.JSONField(blank=True, null=True)),
                ('budget', models.IntegerField(default=0)),
                ('homepage', models.URLField(blank=True)),
                ('id', models.IntegerField(unique=True)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('original_language', models.CharField(max_length=5)),
                ('original_title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField(default=0)),
                ('poster_path', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('revenue', models.BigIntegerField(default=0)),
                ('runtime', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('video', models.BooleanField(default=False)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('genres', models.ManyToManyField(to='api.genre')),
                ('production_companies', models.ManyToManyField(to='api.productioncompany')),
                ('production_countries', models.ManyToManyField(to='api.productioncountry')),
                ('spoken_languages', models.ManyToManyField(to='api.spokenlanguage')),
            ],
        ),
    ]
