# Generated by Django 4.1.10 on 2023-07-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compressed_data', models.BinaryField()),
            ],
        ),
    ]
