# Generated by Django 4.1.9 on 2023-07-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_movie_director_alter_movie_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='expectation',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='private',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='spoiler',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
