# Generated by Django 4.1.9 on 2023-07-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_expectation_review_private_review_spoiler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='synopsis',
        ),
    ]
