# Generated by Django 4.1.9 on 2023-07-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_movie_synopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='expectation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='private',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='spoiler',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
