# Generated by Django 4.1.9 on 2023-07-06 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
