# Generated by Django 4.2 on 2023-07-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mylist",
            old_name="movie_title",
            new_name="media_title",
        ),
        migrations.RenameField(
            model_name="mylist",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AddField(
            model_name="mylist",
            name="media_poster",
            field=models.ImageField(null=True, upload_to="posters/"),
        ),
    ]
