# Generated by Django 4.2 on 2023-07-10 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mypage", "0002_rename_movie_title_mylist_media_title_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GuestNote",
            new_name="GuestBook",
        ),
    ]
