# Generated by Django 4.2.3 on 2023-07-24 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_title', models.CharField(max_length=20)),
                ('media_poster', models.ImageField(null=True, upload_to='posters/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
