# Generated by Django 4.1.9 on 2023-07-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='mylist',
            table='Mylist',
        ),
    ]
