# Generated by Django 4.1.9 on 2023-07-28 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlist', '0002_mylist_like_alter_mylist_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='like',
        ),
        migrations.RemoveField(
            model_name='mylist',
            name='media_poster',
        ),
    ]
