# Generated by Django 4.2.3 on 2023-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='re_comment',
            field=models.TextField(null=True),
        ),
    ]
