# Generated by Django 4.2.3 on 2023-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='movie',
        ),
        migrations.AddField(
            model_name='review',
            name='movie_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
