# Generated by Django 4.2.3 on 2023-07-13 02:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_comments_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
        migrations.AddField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
