# Generated by Django 4.2.3 on 2023-07-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_comments_re_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='re_comment',
            new_name='comment_txt',
        ),
    ]
