# Generated by Django 4.2.3 on 2023-07-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_comments_created_at_comments_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
