# Generated by Django 4.2 on 2023-07-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", models.CharField(max_length=1000)),
                ("edit_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_id", models.IntegerField()),
                ("content", models.CharField(max_length=1000)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("like_count", models.IntegerField()),
                ("writer", models.CharField(max_length=500)),
            ],
        ),
    ]
