<<<<<<< HEAD
# Generated by Django 4.2 on 2023-07-06 02:45
=======
# Generated by Django 4.2.2 on 2023-07-11 02:43
>>>>>>> 53f33647e7fa74b3cc233d2223e57fd57787ce62

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 53f33647e7fa74b3cc233d2223e57fd57787ce62
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1000)),
                ('edit_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateField(auto_now_add=True)),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("content", models.CharField(max_length=1000)),
                ("create_date", models.DateField(auto_now_add=True)),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                ("n_hit", models.PositiveIntegerField(default=0)),
                (
                    "voter",
                    models.ManyToManyField(
                        related_name="voter_post", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_writer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
>>>>>>> 53f33647e7fa74b3cc233d2223e57fd57787ce62
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.IntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField()),
                ('writer', models.CharField(max_length=500)),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="board.board",
                    ),
                ),
                (
                    "voter",
                    models.ManyToManyField(
                        related_name="voter_comment", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "writer",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_writer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
>>>>>>> 53f33647e7fa74b3cc233d2223e57fd57787ce62
            ],
        ),
    ]
