# Generated by Django 4.2.2 on 2023-07-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="created_at",
            new_name="create_date",
        ),
    ]
