# Generated by Django 4.2.2 on 2023-07-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_rename_created_at_board_create_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="board_id",
        ),
        migrations.AddField(
            model_name="comment",
            name="board",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="board.board",
            ),
        ),
    ]
