# Generated by Django 4.2.2 on 2023-07-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_remove_comment_board_id_comment_board"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
