# Generated by Django 4.2.2 on 2023-07-07 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0005_alter_comment_writer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="writer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_writer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
