# Generated by Django 4.2.2 on 2023-07-07 08:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0009_alter_comment_writer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="edit_date",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="like_count",
        ),
        migrations.AddField(
            model_name="board",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="board",
            name="voter",
            field=models.ManyToManyField(
                related_name="voter_post", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="voter",
            field=models.ManyToManyField(
                related_name="voter_comment", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
