# Generated by Django 4.2.2 on 2023-07-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0010_remove_board_edit_date_remove_comment_like_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="n_hit",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
