# Generated by Django 4.2 on 2023-07-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_delete_board_delete_comment"),
        ("board", "0014_alter_board_n_hit"),
    ]

    operations = []
